#!/bin/bash
# Arch Linux setup: dwm suite + pywal + oh-my-zsh + fonts

set -e

# --- Install yay ---
if ! command -v yay >/dev/null 2>&1; then
    echo "Installing yay..."
    sudo pacman -S --needed --noconfirm git base-devel
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si --noconfirm
    cd ~
fi

# --- Install packages ---
echo "Installing dwm, dmenu, st, dwmblocks, powerlevel10k, pywal, and fonts..."
yay -S --needed --noconfirm \
    dwm \
    dmenu \
    st \
    dwmblocks \
    zsh-theme-powerlevel10k \
    ttf-jetbrains-mono \
    noto-fonts-emoji \
    noto-fonts-cjk \
    pywal

# --- Setup pywal templates for dmenu ---
mkdir -p ~/.config/wal/templates
cat > ~/.config/wal/templates/colors-wal-dmenu.h <<'EOF'
/* Generated by pywal for dmenu */
static const char *colors[][3] = {
    /*     fg         bg         border   */
    [SchemeNorm] = { "{foreground}", "{background}", "{color0}" },
    [SchemeSel]  = { "{background}", "{color2}",     "{color2}" },
    [SchemeOut]  = { "{color0}",     "{color2}",     "{color2}" },
};
EOF

# --- Generate initial wal colors ---
if [ -f wallpapers/0001.jpg ]; then
    wal -i wallpapers/0001.jpg
else
    echo "Warning: wallpapers/0001.jpg not found. Skipping wal color generation."
fi

# --- Rebuild dmenu after wal colors exist ---
if [ -d ~/dmenu ]; then
    cd ~/dmenu
    make clean install
    cd ~
fi

# --- Install zsh ---
if ! command -v zsh >/dev/null 2>&1; then
    sudo pacman -S --needed --noconfirm zsh
fi

# --- Backup .zshrc ---
[ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/.zshrc.bak"

# --- Install Oh My Zsh ---
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    export RUNZSH=no
    export CHSH=no
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# --- Set Zsh default ---
if [ "$SHELL" != "$(which zsh)" ]; then
    chsh -s "$(which zsh)"
fi

echo "✅ Setup complete!"

